### ISSUE TITLE
Players Explorer - Sort not working

### ISSUE THREAD

**Issue by lukebiddell** [bapairaew/open-fpl#27]
Sorting doesn't seem to work in Players Explorer. Currently, it only works when sorting by Points.

![image](https://user-images.githubusercontent.com/18555718/129567050-24a69ae4-c3b7-403d-abc5-163558ff305c.png)

Tested on MacOS, Chrome Version 92.0.4515.107 (Official Build) (x86_64)

**Comment by bapairaew** [comment]
Thanks for reporting. This should be fixed later this week.

---

Note

Working: Name, Team, Pos., Cost, Own., Fixtures, Points
Not working: Goals, Assists, Shots, Key passes, xG, xA, xGA 

Side note: negative Points should not highlighted in green
